# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-axolotl"
BBFILE_PATTERN_meta-axolotl = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-axolotl = "6"

LAYERDEPENDS_meta-axolotl = "core"
LAYERSERIES_COMPAT_meta-axolotl = "whinlatter"
